export default defineEventHandler(() => {
  // Replace this array with your actual data
  // For YouTube URLs, use either:
  // - Full URL: https://www.youtube.com/watch?v=VIDEO_ID
  // - Short URL: https://youtu.be/VIDEO_ID
  const videos = [
    {
      id: 0,
      slug: "00-presentacion-devocionales-de-adviento",
      title: "Presentación Devocionales de Adviento",
      person: "Samuel Barbosa",
      verse: "",
      url: "https://www.youtube.com/watch?v=NxOZsLCOzPg",
      thumbnailUrl: "https://img.youtube.com/vi/NxOZsLCOzPg/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-11-30T09:00:00.000Z"),
    },
    {
      id: 1,
      slug: "01-el-verbo-en-el-principio",
      title: "El verbo en el principio",
      person: "Juan Gallego",
      verse: "Genesis 1:1",
      url: "https://www.youtube.com/watch?v=fzjoEckzEvY",
      thumbnailUrl: "https://img.youtube.com/vi/fzjoEckzEvY/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-01T09:00:00.000Z"),
    },
    {
      id: 2,
      slug: "02-la-primera-promesa",
      title: "La primera promesa",
      person: "Ángel David Nicolás Caño",
      verse: "Genesis 3:15",
      url: "https://www.youtube.com/watch?v=6t2RjXnnFI4",
      thumbnailUrl: "https://img.youtube.com/vi/6t2RjXnnFI4/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-02T09:00:00.000Z"),
    },
    {
      id: 3,
      slug: "03-a-la-espera-de-jesus",
      title: "A la espera de Jesús",
      person: "Stevens Lopesierra",
      verse: "Isaias 9:6",
      url: "https://www.youtube.com/watch?v=1F2vDM3E8ss",
      thumbnailUrl: "https://img.youtube.com/vi/1F2vDM3E8ss/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-03T09:00:00.000Z"),
    },
    {
      id: 4,
      slug: "04-del-cordero-se-encargara-dios",
      title: "Del Cordero se encargará Dios",
      person: "Timoteo Anderson",
      verse: "Génesis 12:2-3",
      url: "https://www.youtube.com/watch?v=nbt1C6kHw1I",
      thumbnailUrl: "https://img.youtube.com/vi/nbt1C6kHw1I/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-04T09:00:00.000Z"),
    },
    {
      id: 5,
      slug: "05-el-senor-se-acuerda",
      title: "El Señor se acuerda",
      person: "Juan Carlos Pineda",
      verse: "1 Samuel 1:19-20",
      url: "https://www.youtube.com/watch?v=Fidlj1Skvf8",
      thumbnailUrl: "https://img.youtube.com/vi/Fidlj1Skvf8/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-05T09:00:00.000Z"),
    },
    {
      id: 6,
      slug: "06-habitara-dios-en-la-tierra",
      title: "¿Habitará Dios en La Tierra?",
      person: "Eduardo Torres",
      verse: "2 Cronicas 6:18",
      url: "https://www.youtube.com/watch?v=5ssczZzoFCY",
      thumbnailUrl: "https://img.youtube.com/vi/5ssczZzoFCY/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-06T09:00:00.000Z"),
    },
    {
      id: 7,
      slug: "07-una-luz-resplandecio",
      title: "Una luz resplandeció",
      person: "Pedro Palencia",
      verse: "Isaias 9:2",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-07T09:00:00.000Z"),
    },
    {
      id: 8,
      slug: "08-nos-ha-nacido-un-nino",
      title: "Nos ha nacido un niño",
      person: "Carlos Murillo",
      verse: "Isaias 9:6",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-08T09:00:00.000Z"),
    },
    {
      id: 9,
      slug: "09-noticias-de-gozo-y-paz",
      title: "Noticias de gozo y paz",
      person: "Felipe Tordecilla",
      verse: "Isaias 40:1, 3-5",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-09T09:00:00.000Z"),
    },
    {
      id: 10,
      slug: "10-oh-pueblecito-de-belen",
      title: "Oh, pueblecito de Belén",
      person: "Manuel Castro",
      verse: "Miqueas 5:2, 4-5",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-10T09:00:00.000Z"),
    },
    {
      id: 11,
      slug: "11-el-cumplimiento-de-todas-las-promesas",
      title: "El cumplimiento de todas las promesas",
      person: "Felipe Matamoros",
      verse: "Mateo 1:1",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-11T09:00:00.000Z"),
    },
    {
      id: 12,
      slug: "12-asombro-y-misterio",
      title: "Asombro y misterio",
      person: "Timoteo Anderson",
      verse: "Lucas 1:31, 34-35",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-11T09:00:00.000Z"),
    },
    {
      id: 13,
      slug: "13-cuan-dulce-el-nombre",
      title: "Cuán dulce el nombre",
      person: "Carlos Murillo",
      verse: "Mateo 1:20-21",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-13T09:00:00.000Z"),
    },
    {
      id: 14,
      slug: "14-una-historia-sobrenatural",
      title: "Una historia sobrenatural",
      person: "Eduardo Torres",
      verse: "Lucas 2:1-6",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-14T09:00:00.000Z"),
    },
    {
      id: 15,
      slug: "15-ve-y-dilo",
      title: "Ve y dilo",
      person: "Felipe Tordecilla",
      verse: "Lucas 2:15-17",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-15T09:00:00.000Z"),
    },
    {
      id: 16,
      slug: "16-los-sabios-adoran",
      title: "Los sabios adoran",
      person: "Pedro Palencia",
      verse: "Mateo 2:1-2, 9-11",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-16T09:00:00.000Z"),
    },
    {
      id: 17,
      slug: "17-una-luz-en-la-oscuridad",
      title: "Una luz en la oscuridad",
      person: "Juan Carlos Pineda",
      verse: "Juan 1:5",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-17T09:00:00.000Z"),
    },
    {
      id: 18,
      slug: "18-yo-ire",
      title: "Yo iré",
      person: "Juan Gallego",
      verse: "Hebreos 1:2-3",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-18T09:00:00.000Z"),
    },
    {
      id: 19,
      slug: "19-el-regalo-de-la-adopcion",
      title: "El regalo de la adopción",
      person: "Steven´s Lopesierra",
      verse: "Gálatas 4:4-7",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-19T09:00:00.000Z"),
    },
    {
      id: 20,
      slug: "20-se-despojo-a-si-mismo",
      title: "Se despojó a Sí mismo",
      person: "Samuel Barbosa",
      verse: "Filipenses 2:5-8",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-20T09:00:00.000Z"),
    },
    {
      id: 21,
      slug: "21-la-navidad-en-trece-palabras",
      title: "La Navidad en trece palabras",
      person: "Manuel Castro",
      verse: "Tito 2:11",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-21T09:00:00.000Z"),
    },
    {
      id: 22,
      slug: "22-la-cuna-y-la-cruz",
      title: "La cuna y la cruz",
      person: "Timoteo Anderson",
      verse: "1 Juan 4:10",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-22T09:00:00.000Z"),
    },
    {
      id: 23,
      slug: "23-venga-tu-reino",
      title: "Venga tu Reino",
      person: "Eduardo Torres",
      verse: "Apocalipsis 11:15",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-23T09:00:00.000Z"),
    },
    {
      id: 24,
      slug: "24-con-la-mirada-hacia-adelante",
      title: "Con la mirada hacia adelante",
      person: "Felipe Matamoros",
      verse: "Apocalipsis 21:1-4",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-24T09:00:00.000Z"),
    },
    {
      id: 25,
      slug: "25-despues-de-la-navidad",
      title: "Después de la Navidad",
      person: "Samuel Barbosa",
      verse: "Lucas 1:46-47, 53",
      url: "https://www.youtube.com/watch?v=PLACEHOLDER",
      thumbnailUrl: "https://img.youtube.com/vi/PLACEHOLDER/mqdefault.jpg",
      markdownContent: "",
      displayAfter: new Date("2025-12-25T09:00:00.000Z"),
    },
  ];

  return videos;
});
